
ENV_FILE_PATHS_PER_USER:
  DB:
    - "/tmp/db.env"
    - "/tmp/subscription_manager.env"
  SM_ADMIN:
    - "/tmp/subscription_manager.env"
  SWIM_ADSB:
    - "/tmp/subscription_manager.env"
    - "/tmp/swim_adsb.env"
  SWIM_EXPLORER:
    - "/tmp/subscription_manager.env"
    - "/tmp/swim_explorer.env"
