version: "3.5"


# TODO: NGINX: Configure request limitations as explained in https://nginx.org/en/docs/http/ngx_http_limit_req_module.html
# TODO: check passwords for spaces
# TODO: move password check in swim-backend
# TODO: check passwords in SM POST /users
# TODO: Try to configure PostgreSQL docker image to use SHA256 for password storage of the Database users, as explained
#       here: https://blog.dbi-services.com/migrating-your-users-from-md5-to-scram-authentication-in-postgresql/
# TODO: pull images from docker hub


services:
  db:
    image: swim-postgres
    build:
      context: ./
      dockerfile: ./services/db/postgres/Dockerfile
    container_name: postgres
    environment:
      - DB_NAME=smdb
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./services/db/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/etc/postgresql.conf
    networks:
      - backend

  broker:
    image: rabbitmq_amqp10
    hostname: rabbitmq
    build:
      context: ./
      dockerfile: ./services/broker/rabbitmq/Dockerfile
    container_name: rabbitmq
    ports:
      - 15671:15671
    volumes:
      - broker-data:/var/lib/rabbitmq
    networks:
      - backend

  web-server:
    image: swim-nginx
    build:
      context: ./
      dockerfile: ./services/web_server/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/web_server/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - subscription-manager
    networks:
      - backend

  subscription-manager:
    image: subscription-manager
    build: ./services/subscription_manager/src
    container_name: subscription_manager
    depends_on:
      - db
      - broker
    environment:
      - DB_NAME=smdb
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - BROKER_MGMT_USER=${BROKER_MGMT_USER}
      - BROKER_MGMT_PASS=${BROKER_MGMT_PASS}
    volumes:
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/ca_certificate.pem
      - ./services/subscription_manager/config.yml:/app/subscription_manager/_config.yml
      - ./services/subscription_manager/entry.sh:/app/entry.sh
    command: bash /app/entry.sh
    networks:
      - backend

  subscription-manager-provision:
    image: subscription-manager
    build: ./services/subscription_manager/src
    container_name: subscription_manager_provision
    depends_on:
      - broker
      - db
    environment:
      - DB_NAME=smdb
      - SWIM_EXPLORER_BROKER_USER=${SWIM_EXPLORER_BROKER_USER}
      - SWIM_EXPLORER_BROKER_PASS=${SWIM_EXPLORER_BROKER_PASS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SM_ADMIN_USER=${SM_ADMIN_USER}
      - SM_ADMIN_PASS=${SM_ADMIN_PASS}
      - SWIM_ADSB_SM_USER=${SWIM_ADSB_SM_USER}
      - SWIM_ADSB_PASS=${SWIM_ADSB_PASS}
      - SWIM_EXPLORER_SM_USER=${SWIM_EXPLORER_SM_USER}
      - SWIM_EXPLORER_PASS=${SWIM_EXPLORER_PASS}
      - BROKER_MGMT_USER=${BROKER_MGMT_USER}
      - BROKER_MGMT_PASS=${BROKER_MGMT_PASS}
    volumes:
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/ca_certificate.pem
      - ./services/subscription_manager/provision/config.yml:/app/provision/_config.yml
      - ./services/subscription_manager/provision/entry.sh:/app/entry.sh
    command: bash entry.sh
    networks:
      - backend

  swim-adsb:
    image: swim-adsb
    build: ./services/swim_adsb/src
    container_name: swim_adsb
    depends_on:
      - subscription-manager
      - web-server
    environment:
      - SWIM_ADSB_SM_USER=${SWIM_ADSB_SM_USER}
      - SWIM_ADSB_PASS=${SWIM_ADSB_PASS}
    volumes:
      - ./secrets/rabbitmq/client/:/secrets/broker/client
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/broker/ca_certificate.pem
      - ./secrets/nginx/ca_certificate.pem:/secrets/web_server/ca_certificate.pem
      - ./services/swim_adsb/config.yml:/app/swim_adsb/_config.yml
      - ./services/swim_adsb/entry.sh:/app/entry.sh
    command: bash /app/entry.sh
    networks:
      - backend


  swim-explorer:
    image: swim-explorer
    build: ./services/swim_explorer/src
    container_name: swim_explorer
    depends_on:
      - subscription-manager
      - web-server
      - swim-adsb
    environment:
      - SWIM_EXPLORER_BROKER_USER=${SWIM_EXPLORER_BROKER_USER}
      - SWIM_EXPLORER_BROKER_PASS=${SWIM_EXPLORER_BROKER_PASS}
      - SWIM_EXPLORER_SM_USER=${SWIM_EXPLORER_SM_USER}
      - SWIM_EXPLORER_PASS=${SWIM_EXPLORER_PASS}
    volumes:
      - ./secrets/rabbitmq/client/:/secrets/broker/client
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/broker/ca_certificate.pem
      - ./secrets/nginx/ca_certificate.pem:/secrets/web_server/ca_certificate.pem
      - ./services/swim_explorer/config.yml:/app/swim_explorer/_config.yml
      - ./services/swim_explorer/entry.sh:/app/entry.sh
    ports:
      - 5000:5000
    command: bash /app/entry.sh
    networks:
      - backend

  swim-user-config:
    image: swim-user-config
    build: ./services/swim_user_config/src
    container_name: swim_user_config

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
  broker-data:
    driver: local


