version: "2"

# TODO: add ssl on postgres
# TODO: add postgres role in env variables
# TODO: include swim-base image build in the procedure

services:
  db:
    image: swim-postgres
    build:
      context: ./
      dockerfile: ./services/db/postgres/Dockerfile
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./services/db/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    command: postgres -c config_file=/etc/postgresql.conf
    networks:
      - backend

  broker:
    image: rabbitmq_amqp10
    build:
      context: ./
      dockerfile: ./services/broker/rabbitmq/Dockerfile
    container_name: rabbitmq
    ports:
      - 15672:15672
    networks:
      - backend

  web-server:
    image: swim-nginx
    build:
      context: ./
      dockerfile: ./services/web_server/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/web_server/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - subscription-manager
    networks:
      - backend

  subscription-manager:
    image: subscription-manager
    build: ./services/subscription_manager/src
    container_name: subscription_manager
    depends_on:
      - db
      - broker
    environment:
      - SM_ADMIN_USERNAME=${SM_ADMIN_USERNAME}
      - SM_ADMIN_PASSWORD=${SM_ADMIN_PASSWORD}
      - SWIM_ADSB_USERNAME=${SWIM_ADSB_USERNAME}
      - SWIM_ADSB_PASSWORD=${SWIM_ADSB_PASSWORD}
      - SWIM_EXPLORER_USERNAME=${SWIM_EXPLORER_USERNAME}
      - SWIM_EXPLORER_PASSWORD=${SWIM_EXPLORER_PASSWORD}
    volumes:
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/ca_certificate.pem
      - ./services/subscription_manager/config.yml:/app/subscription_manager/dev_config.yml
    ports:
      - 8080:8080
    command: gunicorn -w 1 --bind :8080 subscription_manager.wsgi:app
    networks:
      - backend

  swim-adsb:
    image: swim-adsb
    build: ./services/swim_adsb/src
    container_name: swim_adsb
    depends_on:
      - subscription-manager
    environment:
      - SWIM_ADSB_USERNAME=${SWIM_ADSB_USERNAME}
      - SWIM_ADSB_PASSWORD=${SWIM_ADSB_PASSWORD}
    volumes:
      - ./secrets/rabbitmq/client/:/secrets/broker/client
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/broker/ca_certificate.pem
      - ./secrets/nginx/ca_certificate.pem:/secrets/web_server/ca_certificate.pem
      - ./services/swim_adsb/config.yml:/app/swim_adsb/config.yml
      - ./scripts/wait_for_subscription_manager.sh:/app/wait_for_subscription_manager.sh
    command: bash -c "/app/wait_for_subscription_manager.sh && python /app/swim_adsb/app.py"
    networks:
      - backend

  swim-explorer:
    image: swim-explorer
    build: ./services/swim_explorer/src
    container_name: swim_explorer
    depends_on:
      - subscription-manager
    environment:
      - SWIM_EXPLORER_USERNAME=${SWIM_EXPLORER_USERNAME}
      - SWIM_EXPLORER_PASSWORD=${SWIM_EXPLORER_PASSWORD}
    volumes:
      - ./secrets/rabbitmq/client/:/secrets/broker/client
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/broker/ca_certificate.pem
      - ./secrets/nginx/ca_certificate.pem:/secrets/web_server/ca_certificate.pem
      - ./services/swim_explorer/config.yml:/app/swim_explorer/config.yml
      - ./scripts/wait_for_subscription_manager.sh:/app/wait_for_subscription_manager.sh
    ports:
      - 5000:5000
    command: bash -c "/app/wait_for_subscription_manager.sh && gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind :5000 swim_explorer.app:flask_app"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local