version: "3.5"

# TODO: pull images from docker hub


services:
  db:
    image: swim-postgres
    build:
      context: ./
      dockerfile: ./services/db/postgres/Dockerfile
    container_name: postgres
    env_file:
      - ./services/db/postgres/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./services/db/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/etc/postgresql.conf
    networks:
      - backend

  broker:
    image: rabbitmq_amqp10
    build:
      context: ./
      dockerfile: ./services/broker/rabbitmq/Dockerfile
    container_name: rabbitmq
    ports:
      - 15671:15671
    networks:
      - backend

  web-server:
    image: swim-nginx
    build:
      context: ./
      dockerfile: ./services/web_server/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/web_server/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - subscription-manager
    networks:
      - backend

  subscription-manager:
    image: subscription-manager
    build: ./services/subscription_manager/src
    container_name: subscription_manager
    depends_on:
      - db
      - broker
    env_file:
      - ./services/subscription_manager/.env
    volumes:
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/ca_certificate.pem
      - ./secrets/rabbitmq/.env:/secrets/.env
      - ./services/subscription_manager/config.yml:/app/subscription_manager/_config.yml
      - ./services/subscription_manager/entry.sh:/app/entry.sh
    command: bash /app/entry.sh
    networks:
      - backend

  subscription-manager-provision:
    image: subscription-manager
    build: ./services/subscription_manager/src
    container_name: subscription_manager_provision
    depends_on:
      - db
    env_file:
      - ./services/subscription_manager/.env
    volumes:
      - ./services/subscription_manager/config.yml:/app/provision_data/_config.yml
      - ./services/subscription_manager/provision_data_entry.sh:/app/provision_data_entry.sh
    command: bash provision_data_entry.sh
    networks:
      - backend

  swim-adsb:
    image: swim-adsb
    build: ./services/swim_adsb/src
    container_name: swim_adsb
    depends_on:
      - subscription-manager
      - web-server
    env_file:
      - ./services/swim_adsb/.env
    volumes:
      - ./secrets/rabbitmq/client/:/secrets/broker/client
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/broker/ca_certificate.pem
      - ./secrets/rabbitmq/.env:/secrets/broker/.env
      - ./secrets/nginx/ca_certificate.pem:/secrets/web_server/ca_certificate.pem
      - ./services/swim_adsb/config.yml:/app/swim_adsb/_config.yml
      - ./services/swim_adsb/entry.sh:/app/entry.sh
    command: bash /app/entry.sh
    networks:
      - backend

  swim-explorer:
    image: swim-explorer
    build: ./services/swim_explorer/src
    container_name: swim_explorer
    depends_on:
      - subscription-manager
      - web-server
      - swim-adsb
    env_file:
      - ./services/swim_explorer/.env
    volumes:
      - ./secrets/rabbitmq/client/:/secrets/broker/client
      - ./secrets/rabbitmq/ca_certificate.pem:/secrets/broker/ca_certificate.pem
      - ./secrets/rabbitmq/.env:/secrets/broker/.env
      - ./secrets/nginx/ca_certificate.pem:/secrets/web_server/ca_certificate.pem
      - ./services/swim_explorer/config.yml:/app/swim_explorer/_config.yml
      - ./services/swim_explorer/entry.sh:/app/entry.sh
    ports:
      - 5000:5000
    command: bash /app/entry.sh
    networks:
      - backend

  swim-user-config:
    image: swim-user-config
    build: ./services/swim_user_config/src
    container_name: swim_user_config
    stdin_open: true
    tty: true
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
