version: "2"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/db/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - backend

  rabbitmq:
    image: rabbitmq_amqp10
    build: ./config/broker/rabbitmq
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 15671:15671
      - 5671:5671
      - 5672:5672
      - 1883:1883
      - 8883:8883
    volumes:
      - /secrets:/certs/
    networks:
      - backend

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/web_server/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - backend

  subscription-manager:
    image: subscription-manager
    build: ./apps/subscription-manager
    container_name: subscription_manager
    depends_on:
      - postgres
      - rabbitmq
      - nginx
    environment:
      - SM_ADMIN_USERNAME=${SM_ADMIN_USERNAME}
      - SM_ADMIN_PASSWORD=${SM_ADMIN_PASSWORD}
      - SWIM_ADSB_USERNAME=${SWIM_ADSB_USERNAME}
      - SWIM_ADSB_PASSWORD=${SWIM_ADSB_PASSWORD}
      - SWIM_EXPLORER_USERNAME=${SWIM_EXPLORER_USERNAME}
      - SWIM_EXPLORER_PASSWORD=${SWIM_EXPLORER_PASSWORD}
    volumes:
      - /secrets:/secrets
      - ./config/subscription_manager/config.yml:/app/subscription_manager/dev_config.yml
    ports:
      - 8080:8080
    command: gunicorn -w 1 --bind 0.0.0.0:8080 subscription_manager.wsgi:app
    networks:
      - backend

  swim-adsb:
    image: swim-adsb
    build: ./apps/swim-adsb
    container_name: swim_adsb
    depends_on:
      - subscription-manager
    environment:
      - SWIM_ADSB_USERNAME=${SWIM_ADSB_USERNAME}
      - SWIM_ADSB_PASSWORD=${SWIM_ADSB_PASSWORD}
    volumes:
      - /secrets:/secrets
      - ./config/swim_adsb/config.yml:/app/swim_adsb/config.yml
      - ./scripts/wait_for_subscription_manager.sh:/app/wait_for_subscription_manager.sh
    command: bash -c "/app/wait_for_subscription_manager.sh && python /app/swim_adsb/app.py"
    networks:
      - backend

  swim-explorer:
    image: swim-explorer
    build: ./apps/swim-explorer
    container_name: swim_explorer
    depends_on:
      - subscription-manager
    environment:
      - SWIM_EXPLORER_USERNAME=${SWIM_EXPLORER_USERNAME}
      - SWIM_EXPLORER_PASSWORD=${SWIM_EXPLORER_PASSWORD}
    volumes:
      - /secrets:/secrets
      - ./config/swim_explorer/config.yml:/app/swim_explorer/config.yml
      - ./scripts/wait_for_subscription_manager.sh:/app/wait_for_subscription_manager.sh
    ports:
      - 5000:5000
    command: bash -c "/app/wait_for_subscription_manager.sh && gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind 0.0.0.0:5000 swim_explorer.app:flask_app"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local