LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:
    swim-pubsub:
      level: DEBUG

    proton:
      level: INFO

BROKER:
  host: 'rabbitmq'
  port: 5671
  tsl_enabled: True
  cert_db: '/secrets/ca_certificate.pem'
  cert_file: '/secrets/client_certificate.pem'
  cert_key: '/secrets/client_key.pem'
  cert_password: 'swim-ti'

SUBSCRIPTION-MANAGER:
  host: 'subscription_manager:8080'
  https: false
  timeout: 30
